### ISSUE TITLE
AWK: option unrecognized

### ISSUE THREAD

**Issue by blauer4** [donbowman/kde-auto-rotate#11]
Hi, 
I came around this script to auto-rotate the screen of my 2-in-1 laptop. It works fine under Kubuntu 20.04(kernel 5.6.7). The only issue I found out is that it spits out these error every time I rotate the screen:
```bash
awk: option `-W interactive' unrecognized, ignored
```
Did you meant to use mawk maybe? Because that's the suggestion that I have right now.

**Comment by donbowman** [comment]
yes its possible there are some changes to awk etc. I haven't spent a lot of time maintaining it :)
someone else has the laptop w/ the flip, so i cannot test it.

**Comment by blauer4** [comment]
I could test some of these issue, but i found out that if you use mawk instead of awk, the error message doesn't appear anymore.
Another issue is that it seems that I cannot install the service permanently into the system, but i will probably open another issue if I don't find a solution. 
Would it be possible to disable the keyboard when I turn the screen in other direction than normal?

**Comment by blauer4** [comment]
I'm working on a fix for this problem, it seems that the script works fine with the change from `awk` to `mawk`. In addition I made possible to disable the keyboard when the screen is not positioned in normal position, because it is possible to hit accidentally some keys when you go in tablet mode. I will later do a pull request when I have tested thoroughly the new feature.
